language: ruby
rvm:
- 2.0
- 2.1
- 2.2

script:
- bundle exec rspec

before_script:
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
- bundle exec rake db:drop
- bundle exec rake db:create
- bundle exec rake db:migrate

env:
  global:
  - TRAVIS=1
